version: "3.9"

services:
  ### BACKEND PROD ###
  symfony:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: symfony_app
    restart: always
    volumes:
      - ./backend:/var/www/html
    environment:
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/symfony_db?serverVersion=15&charset=utf8"
      STRIPE_SECRET_KEY: ""
      STRIPE_PUBLIC_KEY: ""
    depends_on:
      - db

  ### NGINX PROD ###
  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony

  ### FRONTEND PROD ###
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: react_client
    environment:
      REACT_APP_STRIPE_PUBLIC_KEY: "pk_live_your_public_key"
    ports:
      - "3000:3000"

  ### DATABASE ###
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: mongodb_no_sql
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
