nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://ecoride-7ryq.onrender.com']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600

    paths:
        '^/api/':
            allow_origin: ['https://ecoride-7ryq.onrender.com']
